//自定义菜单
module.exports = {
    "button":[
        {
            "type":"view",
            "name":"首页",
            "url":"http://www.myyaya.com.cn/getCode"
        },
        {
            "type":"view",
            "name":"登录",
            "url":"http://www.myyaya.com.cn/getCode"
        },
        {
            "type":"view",
            "name":"接口文档",
            "url":"http://www.myyaya.com.cn/share"
        },
    ]
}